name: Update Hugging Face Models

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual run

jobs:
  update_models:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Continue other attempts even if one fails
      max-parallel: 1   # Only one job runs at a time
      matrix:
        attempt: [1, 2, 3]  # Retries up to 3 times if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use your preferred Python version

      - name: Install dependencies
        run: |
          pip install -U huggingface_hub

      - name: Run update_models.py
        run: python update_models.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add outputs/models.json
          git diff --staged --quiet || git commit -m "Update Hugging Face models list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
