name: Update Hugging Face Models

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write  # Required for pushing commits

jobs:
  update-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main  # Run workflow in 'main' branch
          fetch-depth: 0  # Ensure full history for branch operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Run script
        run: python update_models.py

      - name: Move models.txt to temp location
        run: mv models.json /tmp/models.json

      - name: Checkout outputs branch
        run: |
          git fetch origin outputs || git checkout -b outputs origin/outputs
          git checkout outputs

      - name: Move models.txt back and commit
        run: |
          mv /tmp/models.txt models.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add models.json
          git commit -m "Update Hugging Face models list" || echo "No changes to commit"
          git push origin outputs
